# Generated by Django 2.0 on 2018-10-07 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodie_info',
            name='city',
            field=models.CharField(choices=[('zulia', 'Zulia'), ('caracas', 'Caracas'), ('valencia', 'Valencia'), ('barquisimeto', 'Barquisimeto'), ('maracay', 'Maracay'), (' ciudad guayana', ' Ciudad Guayana'), ('san cristobal', 'San Cristobal'), ('barcelona', 'Barcelona'), ('maturin', 'Maturin'), ('ciudad bolivar', 'Ciudad Bolivar'), ('puerto la cruz', 'Puerto La Cruz'), ('merida', 'Merida'), ('punto fijo', 'Punto Fijo'), ('los teques', 'Los Teques'), ('acarigua', 'Acarigua'), ('carabobo', 'Carabobo'), ('valera', 'Valera'), ('apure', 'Apure'), ('coro', 'Coro'), ('puerto cabello', 'Puerto Cabello')], default='caracas', max_length=15),
        ),
        migrations.AlterField(
            model_name='foodie_info',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undenifed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', related_query_name='relationships', to='foodie.RelationShip'),
        ),
    ]
