# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('name', models.CharField(max_length=60)),
                ('rif', models.CharField(max_length=100)),
                ('number_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=45)),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Info',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('mealtype', models.CharField(max_length=15)),
                ('slogan', models.CharField(max_length=112)),
                ('descripcion', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=112)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='User_Star',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undenifed')], max_length=1)),
                ('avatar', models.ImageField(upload_to='user_profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.base',),
        ),
        migrations.AddField(
            model_name='user_star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='users_star_restaurant',
            field=models.ManyToManyField(blank=True, related_name='restaurant_star', to='app.UserProfile'),
        ),
    ]
