# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:17
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[(b'zulia', b'Zulia'), (b'caracas', b'Caracas'), (b'valencia', b'Valencia'), (b'barquisimeto', b'Barquisimeto'), (b'maracay', b'Maracay'), (b' ciudad guayana', b' Ciudad Guayana'), (b'san cristobal', b'San Cristobal'), (b'barcelona', b'Barcelona'), (b'maturin', b'Maturin'), (b'ciudad bolivar', b'Ciudad Bolivar'), (b'puerto la cruz', b'Puerto La Cruz'), (b'merida', b'Merida'), (b'punto fijo', b'Punto Fijo'), (b'los teques', b'Los Teques'), (b'acarigua', b'Acarigua'), (b'carabobo', b'Carabobo'), (b'valera', b'Valera'), (b'apure', b'Apure'), (b'coro', b'Coro'), (b'puerto cabello', b'Puerto Cabello')], default='caracas', max_length=15)),
                ('address', models.CharField(default='undefined', max_length=112)),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', app.models.IntegerRangeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Review',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('text', models.CharField(max_length=120)),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Food_Dishes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('only_ofert', models.CharField(choices=[('yes', 'Yes only ofert'), ('no', 'No only ofert')], max_length=3)),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=45)),
                ('mealtype', models.CharField(default='None', max_length=20)),
                ('prize', models.FloatField(default=0)),
                ('photo', models.ImageField(default='food_dishes/default.jpg', upload_to='food_dishes/')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('rif', models.CharField(max_length=100, unique=True)),
                ('number_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=45, unique=True)),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Info',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('mealtype', models.CharField(max_length=15)),
                ('slogan', models.CharField(max_length=112)),
                ('descripcion', models.CharField(max_length=300)),
                ('city', models.CharField(choices=[(b'zulia', b'Zulia'), (b'caracas', b'Caracas'), (b'valencia', b'Valencia'), (b'barquisimeto', b'Barquisimeto'), (b'maracay', b'Maracay'), (b' ciudad guayana', b' Ciudad Guayana'), (b'san cristobal', b'San Cristobal'), (b'barcelona', b'Barcelona'), (b'maturin', b'Maturin'), (b'ciudad bolivar', b'Ciudad Bolivar'), (b'puerto la cruz', b'Puerto La Cruz'), (b'merida', b'Merida'), (b'punto fijo', b'Punto Fijo'), (b'los teques', b'Los Teques'), (b'acarigua', b'Acarigua'), (b'carabobo', b'Carabobo'), (b'valera', b'Valera'), (b'apure', b'Apure'), (b'coro', b'Coro'), (b'puerto cabello', b'Puerto Cabello')], default='caracas', max_length=15)),
                ('address', models.CharField(max_length=112)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Media',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('banner', models.ImageField(default='restaurant_banner/default.jpg', upload_to='restaurant_banner/')),
                ('picture', models.ImageField(default='restaurant_picture/default.jpg', upload_to='restaurant_picture/')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Review',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('text', models.CharField(max_length=240)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'u', b'Undenifed')], max_length=1)),
                ('avatar', models.ImageField(default='user_profile/default.jpg', upload_to='user_profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.base',),
        ),
        migrations.AddField(
            model_name='user_star',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='user_star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
        migrations.AddField(
            model_name='restaurantsucursal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='restaurant_review_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food_dishes',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish_review',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Food_Dishes'),
        ),
        migrations.AddField(
            model_name='dish_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
        migrations.AddField(
            model_name='dish_review',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='dish_review_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
