# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undenifed')], max_length=1)),
                ('avatar', models.ImageField(upload_to='user_profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.base',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='users_star_restaurant',
            field=models.ManyToManyField(blank=True, related_name='restaurant_star', to='app.User_Star'),
        ),
        migrations.AlterField(
            model_name='user_star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
