# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 01:34
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170111_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Dishes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('only_ofert', models.CharField(choices=[('yes', 'Yes only ofert'), ('no', 'No only ofert')], max_length=3)),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=45)),
                ('mealtype', models.CharField(default='None', max_length=20)),
                ('prize', models.FloatField(default=0)),
                ('photo', models.ImageField(upload_to='food_dishes/')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Media',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('banner', models.ImageField(upload_to='restaurant_banner/')),
                ('picture', models.ImageField(upload_to='restaurant_picture/')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='RestaurantSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=112)),
            ],
            bases=('app.base',),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='users_star_restaurant',
        ),
        migrations.AddField(
            model_name='user_star',
            name='calification',
            field=app.models.IntegerRangeField(default=0),
        ),
        migrations.AddField(
            model_name='user_star',
            name='stars',
            field=models.ManyToManyField(to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantsucursal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantsucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sucursal'),
        ),
        migrations.AddField(
            model_name='restaurant_media',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='food_dishes',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sucursales',
            field=models.ManyToManyField(related_name='sucursals_restaurant', through='app.RestaurantSucursal', to='app.Sucursal'),
        ),
    ]
