# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170123_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Review',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('text', models.CharField(max_length=120)),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Restaurant_Review',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Base')),
                ('text', models.CharField(max_length=240)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant')),
            ],
            bases=('app.base',),
        ),
        migrations.RemoveField(
            model_name='restaurantsucursal',
            name='main',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food_dishes',
            name='photo',
            field=models.ImageField(default='food_dishes/default.jpg', upload_to='food_dishes/'),
        ),
        migrations.AlterField(
            model_name='restaurant_media',
            name='banner',
            field=models.ImageField(default='restaurant_banner/default.jpg', upload_to='restaurant_banner/'),
        ),
        migrations.AlterField(
            model_name='restaurant_media',
            name='picture',
            field=models.ImageField(default='restaurant_picture/default.jpg', upload_to='restaurant_picture/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='avatar',
            field=models.ImageField(default='user_profile/default.jpg', upload_to='user_profile/'),
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
        migrations.AddField(
            model_name='dish_review',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Food_Dishes'),
        ),
        migrations.AddField(
            model_name='dish_review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_Info'),
        ),
    ]
