# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170123_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_info',
            name='city',
            field=models.CharField(choices=[('zulia', 'Zulia'), ('caracas', 'Caracas'), ('valencia', 'Valencia'), ('barquisimeto', 'Barquisimeto'), ('maracay', 'Maracay'), (' ciudad guayana', ' Ciudad Guayana'), ('san cristobal', 'San Cristobal'), ('barcelona', 'Barcelona'), ('maturin', 'Maturin'), ('ciudad bolivar', 'Ciudad Bolivar'), ('puerto la cruz', 'Puerto La Cruz'), ('merida', 'Merida'), ('punto fijo', 'Punto Fijo'), ('los teques', 'Los Teques'), ('acarigua', 'Acarigua'), ('carabobo', 'Carabobo'), ('valera', 'Valera'), ('apure', 'Apure'), ('coro', 'Coro'), ('puerto cabello', 'Puerto Cabello')], max_length=15),
        ),
    ]
