# Generated by Django 2.0 on 2018-10-07 08:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodie', '0002_auto_20181007_0800'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_ofert', models.CharField(choices=[('yes', 'Yes only ofert'), ('no', 'No only ofert')], max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=85)),
                ('mealtype', models.CharField(default='None', max_length=20)),
                ('prize', models.FloatField(default=0)),
                ('photo', models.ImageField(default='food_dishes/default.jpg', upload_to='food_dishes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishesLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie')),
            ],
            options={
                'db_table': 'meta_dishes_likes',
            },
        ),
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie')),
                ('users_like', models.ManyToManyField(blank=True, related_name='dish_review_like', to='foodie.Foodie')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('description', models.CharField(max_length=400)),
                ('photo', models.ImageField(default='food_offers/default.jpg', upload_to='food_offers/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, unique=True)),
                ('rif', models.CharField(max_length=100, null=True, unique=True)),
                ('number_phone', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', core.models.IntegerRangeField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype', models.CharField(max_length=15)),
                ('slogan', models.CharField(max_length=112)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMediaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='restaurant_banner/default.jpg', upload_to='restaurant_banner/')),
                ('picture', models.ImageField(default='restaurant_picture/default.jpg', upload_to='restaurant_picture/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie')),
                ('users_like', models.ManyToManyField(blank=True, related_name='restaurant_review_like', to='foodie.Foodie')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie')),
            ],
            options={
                'db_table': 'meta_restaurants_likes',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('zulia', 'Zulia'), ('caracas', 'Caracas'), ('valencia', 'Valencia'), ('barquisimeto', 'Barquisimeto'), ('maracay', 'Maracay'), (' ciudad guayana', ' Ciudad Guayana'), ('san cristobal', 'San Cristobal'), ('barcelona', 'Barcelona'), ('maturin', 'Maturin'), ('ciudad bolivar', 'Ciudad Bolivar'), ('puerto la cruz', 'Puerto La Cruz'), ('merida', 'Merida'), ('punto fijo', 'Punto Fijo'), ('los teques', 'Los Teques'), ('acarigua', 'Acarigua'), ('carabobo', 'Carabobo'), ('valera', 'Valera'), ('apure', 'Apure'), ('coro', 'Coro'), ('puerto cabello', 'Puerto Cabello')], default='caracas', max_length=15)),
                ('address', models.CharField(default='undefined', max_length=112)),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='restaurant_like', through='restaurant.RestaurantsLikes', to='foodie.Foodie'),
        ),
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Offer'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='dish_like', through='restaurant.DishesLikes', to='foodie.Foodie'),
        ),
    ]
