# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_ofert', models.CharField(choices=[(b'yes', b'Yes only ofert'), (b'no', b'No only ofert')], max_length=3)),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=45)),
                ('mealtype', models.CharField(default='None', max_length=20)),
                ('prize', models.FloatField(default=0)),
                ('photo', models.ImageField(default='food_dishes/default.jpg', upload_to='food_dishes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='dish_review_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype', models.CharField(max_length=15)),
                ('slogan', models.CharField(max_length=112)),
                ('descripcion', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='restaurant_banner/default.jpg', upload_to='restaurant_banner/')),
                ('picture', models.ImageField(default='restaurant_picture/default.jpg', upload_to='restaurant_picture/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='restaurant_review_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[(b'zulia', b'Zulia'), (b'caracas', b'Caracas'), (b'valencia', b'Valencia'), (b'barquisimeto', b'Barquisimeto'), (b'maracay', b'Maracay'), (b' ciudad guayana', b' Ciudad Guayana'), (b'san cristobal', b'San Cristobal'), (b'barcelona', b'Barcelona'), (b'maturin', b'Maturin'), (b'ciudad bolivar', b'Ciudad Bolivar'), (b'puerto la cruz', b'Puerto La Cruz'), (b'merida', b'Merida'), (b'punto fijo', b'Punto Fijo'), (b'los teques', b'Los Teques'), (b'acarigua', b'Acarigua'), (b'carabobo', b'Carabobo'), (b'valera', b'Valera'), (b'apure', b'Apure'), (b'coro', b'Coro'), (b'puerto cabello', b'Puerto Cabello')], default='caracas', max_length=15)),
                ('address', models.CharField(default='undefined', max_length=112)),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.Base')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('rif', models.CharField(max_length=100, unique=True)),
                ('number_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=45, unique=True)),
            ],
            bases=('restaurant.base',),
        ),
        migrations.AddField(
            model_name='restaurantsucursal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant_media',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant_info',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
