# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rif',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
