# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='dish_like', to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='dish_review_like', to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='restaurant_like', to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='restaurant_star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Foodie'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='restaurant_review_like', to='foodie.Foodie'),
        ),
    ]
